import "../globals.css";

export const metadata = {
  title: "Person Detections",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return <main>{children}</main>;
}

